name: deploy-gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: make scripts executable  
      run: chmod u+x build.sh
    - name: build 
      working-directory: ./
      run: ./build.sh 
    - name: Build-docs
      working-directory: ./
      run: dotnet fsdocs build --eval
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ./output # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
 
